### ISSUE TITLE
json parsing and jinja templating errors

### ISSUE THREAD

**Issue by nakitamccool** [Code-Institute-Solutions/TheFlaskFramework-FlaskAndData#1]
company.json is missing commas after the image_url values which causes parsing errors.
About page is throwing templating errors (may be to do with loop), will debug it today to find out more.

**Comment by nakitamccool** [comment]
Resolved templating error and updated solution code. 
Video needs to be editing to remove the reference to the second if statement (if we end the video at 3:04, that will resolve the issue - https://youtu.be/3UFAbDd8K8o)
@NielMc @aaronsnig501 Can one of you do this in Camtasia please? I don't have an account!

**Comment by NielMc** [comment]
Corrected jinja loop typo.
